org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.3

# Mod properties
version=0.1.1
group=io.github.accurateblockraycasts
archives_base_name=accurate-block-raycasts
